### ISSUE TITLE
ValueError: 6000000000000 is not a valid Coins

### ISSUE THREAD

**Issue by whileunless** [basicswap/basicswap#101]
All seems to be fine, the daemon continues running but I get this `ValueError` all the time, without clicking on anything at <http://127.0.0.1:12700/> . My `basicswap.log`:
```
2024-06-26 09:23:14 INFO : Network: mainnet
2024-06-26 09:23:14 INFO : Starting Wownero wallet daemon
2024-06-26 09:23:14 DEBUG : 'trusted_daemon' setting for Wownero: auto.
2024-06-26 09:23:14 INFO : daemon-address: 127.0.0.1:34568 (trusted)
2024-06-26 09:23:14 INFO : Started wownero-wallet-rpc 56634
2024-06-26 09:23:14 INFO : Starting Monero wallet daemon
2024-06-26 09:23:14 DEBUG : 'trusted_daemon' setting for Monero: auto.
2024-06-26 09:23:14 INFO : daemon-address: 127.0.0.1:18081 (trusted)
2024-06-26 09:23:14 INFO : Started monero-wallet-rpc 56635
2024-06-26 09:23:14 INFO : Starting Particl daemon
2024-06-26 09:23:14 INFO : Started particld 56636
2024-06-26 09:23:14 INFO : Starting BasicSwap 0.13.4, database v24


2024-06-26 09:23:14 INFO : Python version: 3.10.12
2024-06-26 09:23:14 INFO : SQLAlchemy version: 1.4.39
2024-06-26 09:23:14 INFO : Timezone offset: -3600 (CET)
2024-06-26 09:23:14 DEBUG : Reading PART rpc credentials from auth cookie /home/j/coinswaps/particl/.cookie
2024-06-26 09:23:14 WARNING : Error, iteration 0: [Errno 2] No such file or directory: '/home/j/coinswaps/particl/particl.pid'
2024-06-26 09:23:15 WARNING : Can't connect to PART RPC: RPC error {'code': -28, 'message': 'Loading block index…'}.  Trying again in 1 second/s, 1/21.
2024-06-26 09:23:16 WARNING : Can't connect to PART RPC: RPC error {'code': -28, 'message': 'Loading block index…'}.  Trying again in 2 second/s, 2/21.
2024-06-26 09:23:18 WARNING : Can't connect to PART RPC: RPC error {'code': -28, 'message': 'Loading block index…'}.  Trying again in 3 second/s, 3/21.
2024-06-26 09:23:21 WARNING : Can't connect to PART RPC: RPC error {'code': -28, 'message': 'Loading block index…'}.  Trying again in 4 second/s, 4/21.
2024-06-26 09:23:29 INFO : Particl Core version 23020700
2024-06-26 09:23:29 DEBUG : New PART block at height: 1700085
2024-06-26 09:23:29 INFO : Connecting to remote Monero daemon at 127.0.0.1.
2024-06-26 09:23:29 INFO : Monero Core version 65563
2024-06-26 09:23:29 DEBUG : New XMR block at height: 3179623
2024-06-26 09:23:31 INFO : Connecting to remote Wownero daemon at 127.0.0.1.
2024-06-26 09:23:31 INFO : Wownero Core version 65562
2024-06-26 09:23:31 DEBUG : New WOW block at height: 642403
2024-06-26 09:23:34 DEBUG : network_key ****************************************************
network_pubkey ******************************************************************
network_addr **********************************
2024-06-26 09:23:34 INFO : Loading data from db
2024-06-26 09:23:34 DEBUG : Ignoring message involving inactive coin FIRO, type OFFER
2024-06-26 09:23:34 WARNING : Failed to decode offer, protocol version: 6, Unexpected wire_type 0 for field 14.
2024-06-26 09:23:34 DEBUG : Ignoring message involving inactive coin BTC, type OFFER
2024-06-26 09:23:34 ERROR : processMsg Offer expired
2024-06-26 09:23:34 ERROR : Traceback (most recent call last):
  File "/home/j/coinswaps/venv/lib/python3.10/site-packages/basicswap/basicswap.py", line 6416, in processMsg
    self.processOffer(msg)
  File "/home/j/coinswaps/venv/lib/python3.10/site-packages/basicswap/basicswap.py", line 4826, in processOffer
    ensure(msg['sent'] + offer_data.time_valid >= now, 'Offer expired')
  File "/home/j/coinswaps/venv/lib/python3.10/site-packages/basicswap/util/__init__.py", line 46, in ensure
    raise ValueError(err_string)
ValueError: Offer expired

2024-06-26 09:23:34 WARNING : Incoming offer invalid protocol version: 3.
2024-06-26 09:23:34 DEBUG : Ignoring message involving inactive coin LTC, type OFFER
2024-06-26 09:23:34 DEBUG : Ignoring message involving inactive coin DCR, type OFFER
2024-06-26 09:23:34 WARNING : Failed to decode offer, protocol version: 6, Unexpected wire_type 0 for field 14.
2024-06-26 09:23:34 DEBUG : Ignoring message involving inactive coin BTC, type OFFER
2024-06-26 09:23:34 DEBUG : Ignoring message involving inactive coin BTC, type OFFER
2024-06-26 09:23:34 DEBUG : Ignoring message involving inactive coin FIRO, type OFFER
2024-06-26 09:23:34 DEBUG : Ignoring message involving inactive coin BTC, type OFFER
2024-06-26 09:23:34 DEBUG : Ignoring message involving inactive coin LTC, type OFFER
2024-06-26 09:23:34 DEBUG : Received new offer 00000000667bc1ec7dcd17e9698d86aeaca40d63875104789f2a3089
2024-06-26 09:23:34 INFO : Scanned 14 unread messages.
2024-06-26 09:23:34 INFO : Starting http server at http://127.0.0.1:12700.
2024-06-26 09:23:34 INFO : Starting ws server at ws://127.0.0.1:11700.
2024-06-26 09:23:34 DEBUG : Ignoring message involving inactive coin FIRO, type OFFER
2024-06-26 09:23:34 DEBUG : Expired 0 bids and 1 offer
2024-06-26 09:23:34 INFO : Expired 12 / 55 messages.
2024-06-26 09:23:35 WARNING : Failed to decode offer, protocol version: 6, Unexpected wire_type 0 for field 14.
2024-06-26 09:23:35 DEBUG : Ignoring message involving inactive coin BTC, type OFFER
2024-06-26 09:23:36 ERROR : processMsg Offer expired
2024-06-26 09:23:36 ERROR : Traceback (most recent call last):
  File "/home/j/coinswaps/venv/lib/python3.10/site-packages/basicswap/basicswap.py", line 6416, in processMsg
    self.processOffer(msg)
  File "/home/j/coinswaps/venv/lib/python3.10/site-packages/basicswap/basicswap.py", line 4826, in processOffer
    ensure(msg['sent'] + offer_data.time_valid >= now, 'Offer expired')
  File "/home/j/coinswaps/venv/lib/python3.10/site-packages/basicswap/util/__init__.py", line 46, in ensure
    raise ValueError(err_string)
ValueError: Offer expired

2024-06-26 09:23:36 WARNING : Incoming offer invalid protocol version: 3.
2024-06-26 09:23:37 DEBUG : Ignoring message involving inactive coin LTC, type OFFER
2024-06-26 09:23:37 DEBUG : Ignoring message involving inactive coin DCR, type OFFER
2024-06-26 09:23:38 WARNING : Failed to decode offer, protocol version: 6, Unexpected wire_type 0 for field 14.
2024-06-26 09:23:38 DEBUG : Ignoring message involving inactive coin BTC, type OFFER
2024-06-26 09:23:39 DEBUG : Ignoring message involving inactive coin BTC, type OFFER
2024-06-26 09:23:40 DEBUG : Ignoring message involving inactive coin FIRO, type OFFER
2024-06-26 09:23:40 DEBUG : Ignoring message involving inactive coin BTC, type OFFER
2024-06-26 09:23:41 DEBUG : Ignoring message involving inactive coin LTC, type OFFER
2024-06-26 09:23:52 DEBUG : New PART block at height: 1700090
2024-06-26 09:24:12 DEBUG : New XMR block at height: 3179624
2024-06-26 09:24:16 ERROR : processMsg 6000000000000 is not a valid Coins
2024-06-26 09:24:16 ERROR : Traceback (most recent call last):
  File "/home/j/coinswaps/venv/lib/python3.10/site-packages/basicswap/basicswap.py", line 6416, in processMsg
    self.processOffer(msg)
  File "/home/j/coinswaps/venv/lib/python3.10/site-packages/basicswap/basicswap.py", line 4817, in processOffer
    coin_to = Coins(offer_data.coin_to)
  File "/usr/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 6000000000000 is not a valid Coins

2024-06-26 09:24:34 INFO : Expired 1 / 44 messages.
2024-06-26 09:24:41 DEBUG : New XMR block at height: 3179625
2024-06-26 09:25:34 INFO : Expired 0 / 43 messages.
2024-06-26 09:26:13 DEBUG : New WOW block at height: 642404
2024-06-26 09:26:29 DEBUG : Ignoring message involving inactive coin DCR, type OFFER
2024-06-26 09:26:34 INFO : Expired 1 / 44 messages.
2024-06-26 09:26:44 DEBUG : Ignoring message involving inactive coin BTC, type OFFER
2024-06-26 09:26:45 DEBUG : New XMR block at height: 3179626
2024-06-26 09:27:12 WARNING : Incoming offer invalid protocol version: 3.
2024-06-26 09:27:34 INFO : Expired 1 / 45 messages.
2024-06-26 09:27:53 INFO : Stopping websocket server.
2024-06-26 09:27:53 INFO : Finalise
2024-06-26 09:27:53 INFO : Stopping HTTP threads.
2024-06-26 09:27:53 INFO : Interrupting 56634
2024-06-26 09:27:53 INFO : Interrupting 56635
2024-06-26 09:27:53 INFO : Interrupting 56636

```
My `basicswap.json` 
```
{
    "debug": true,
    "zmqhost": "tcp://127.0.0.1",
    "zmqport": 20792,
    "htmlhost": "127.0.0.1",
    "htmlport": 12700,
    "network_key": "****************************************************",
    "network_pubkey": "******************************************************************",
    "chainclients": {
        "wownero": {
            "connection_type": "rpc",
            "manage_daemon": false,
            "manage_wallet_daemon": true,
            "rpcport": 34568,
            "zmqport": 34698,
            "walletrpcport": 34798,
            "rpchost": "127.0.0.1",
            "trusted_daemon": "auto",
            "walletrpchost": "127.0.0.1",
            "walletrpcuser": "wow_wallet_user",
            "walletrpcpassword": "wow_wallet_pwd",
            "walletfile": "swap_wallet",
            "datadir": "/home/j/coinswaps/wownero",
            "bindir": "/home/j/coinswaps/bin/wownero",
            "restore_height": 600000,
            "blocks_confirmed": 2,
            "rpctimeout": 60,
            "walletrpctimeout": 120,
            "walletrpctimeoutlong": 300,
            "core_type_group": "xmr",
            "walletsdir": "/home/j/coinswaps/wownero"
        },
        "monero": {
            "connection_type": "rpc",
            "manage_daemon": false,
            "manage_wallet_daemon": true,
            "rpcport": 18081,
            "zmqport": 30898,
            "walletrpcport": 29998,
            "rpchost": "127.0.0.1",
            "trusted_daemon": "auto",
            "walletrpchost": "127.0.0.1",
            "walletrpcuser": "xmr_wallet_user",
            "walletrpcpassword": "xmr_wallet_pwd",
            "walletfile": "swap_wallet",
            "datadir": "/home/j/coinswaps/monero",
            "bindir": "/home/j/coinswaps/bin/monero",
            "restore_height": 3177015,
            "blocks_confirmed": 3,
            "rpctimeout": 60,
            "walletrpctimeout": 120,
            "walletrpctimeoutlong": 600,
            "core_type_group": "xmr",
            "walletsdir": "/home/j/coinswaps/monero"
        },
        "particl": {
            "connection_type": "rpc",
            "manage_daemon": true,
            "rpchost": "127.0.0.1",
            "rpcport": 19792,
            "onionport": 51734,
            "datadir": "/home/j/coinswaps/particl",
            "bindir": "/home/j/coinswaps/bin/particl",
            "blocks_confirmed": 2,
            "override_feerate": 0.002,
            "conf_target": 2,
            "core_version_group": 21
        }
    },
    "min_delay_event": 5,
    "max_delay_event": 50,
    "check_progress_seconds": 60,
    "check_watched_seconds": 60,
    "check_expired_seconds": 60,
    "wallet_update_timeout": 10,
    "wshost": "127.0.0.1",
    "wsport": 11700,
    "tor_control_password": "**********",
    "use_tor": false,
    "tor_proxy_host": "127.0.0.1",
    "tor_proxy_port": 9050,
    "tor_control_port": 9051
}
```
Instalation with `https://github.com/nahuhh/basicswap-bash/install.sh`.

**Comment by snex** [comment]
It seems like max WOW is set to 10,000 in https://github.com/basicswap/basicswap/blob/master/basicswap/chainparams.py. This value is way way too low.
