### ISSUE TITLE
Windows installer errors out with python errors at 70%

### ISSUE THREAD

**Issue by vandonsel** [basicswap/basicswap#104]
Steps to produce:
1. Run Windows installer as admin
2. Pick wherever for install dir
3. Continue

Result: Stuck on 80%
Errors are as follows
![chqarezuWo](https://github.com/basicswap/basicswap/assets/8953804/64306d1a-9be2-4a2e-a3fb-2b614526e85c)

##############################################################################
# 12 Preparing Basicswap.
##############################################################################

[INFO] Preparing BasicSwap...
[INFO] Preparing Monero setup. Fetching current XMR height...
[INFO] Monero selected. Current XMR height: 3188774
PROGRESS: 70
[INFO] Starting basicswap-prepare for Monero. This might take a while..
[ALERT]: Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Scripts\basicswap-prepare.exe\__main__.py", line 4, in <module>

[ALERT]:   File "C:\Python312\Lib\site-packages\bin\basicswap_prepare.py", line 33, in <module>

[ALERT]:     from basicswap.basicswap import BasicSwap
  File "C:\Python312\Lib\site-packages\basicswap\basicswap.py", line 69, in <module>

[ALERT]:     from .messages_pb2 import (
  File "C:\Python312\Lib\site-packages\basicswap\messages_pb2.py", line 9, in <module>

[ALERT]:     from google.protobuf import runtime_version as _runtime_version

[ALERT]: ImportError: cannot import name 'runtime_version' from 'google.protobuf' (C:\Python312\Lib\site-packages\google\protobuf\__init__.py)

[INFO] BasicSwap with Monero setup and download completed.
[INFO] Setup and installation completed.
Child process exited with code 0

**Comment by nahuhh** [comment]
Windows GUI installer hasn't been updated yet. Won't work, sorry

**Comment by bsqfees24** [comment]
Same error. When will the windows installer be fixed?
