### ISSUE TITLE
'Mismatched pid' error after basicswap daemon shut down unexpectedly

### ISSUE THREAD

**Issue by terriblenecktie** [basicswap/basicswap#105]
I'm running basicswap via docker. While the coins were syncing it crashed due to file storage issues and I don't think it shut down gracefully. When I tried to `docker compose up` again I get an error when it tries to read the cookie.
```
swapclient-1  | 2024-07-11 17:59:25 WARNING : Error, iteration 19: [Errno 2] No such file or directory: '/coindata/particl/particl.pid'
swapclient-1  | 2024-07-11 17:59:25 ERROR : Unable to read authcookie for PART, /coindata/particl/.cookie, datadir pid -1, daemon pid 18. Error: Mismatched pid
swapclient-1  | Traceback (most recent call last):
swapclient-1  |   File "/usr/local/lib/python3.10/dist-packages/basicswap/basicswap.py", line 769, in setCoinRunParams
swapclient-1  |     assert (datadir_pid == cc['pid']), 'Mismatched pid'
swapclient-1  | AssertionError: Mismatched pid
swapclient-1  | 
swapclient-1  | During handling of the above exception, another exception occurred:
swapclient-1  | 
swapclient-1  | Traceback (most recent call last):
swapclient-1  |   File "/usr/local/lib/python3.10/dist-packages/bin/basicswap_run.py", line 302, in runClient
swapclient-1  |     swap_client.start()
swapclient-1  |   File "/usr/local/lib/python3.10/dist-packages/basicswap/basicswap.py", line 798, in start
swapclient-1  |     self.setCoinRunParams(c)
swapclient-1  |   File "/usr/local/lib/python3.10/dist-packages/basicswap/basicswap.py", line 774, in setCoinRunParams
swapclient-1  |     raise ValueError('Error, terminating')
swapclient-1  | ValueError: Error, terminating
```
Is there any way I can fix this? I've tried to fiddle with the code but I can't seem to get it to finish the `setCoinRunParams` method without erroring. The only part that seems to matter in that is setting the `cc['rpcauth']` and I tried various defaults for this but couldn't get it to work fully. Can I somehow manually supply rpcauth or set a default cookie somehow? 

Once I can get it running again I'll make sure it shuts down gracefully. I would just prefer not to have to delete the entire chain sync's progress to get it working.

**Comment by nahuhh** [comment]
particld is still running / wasnt shut down. If you cant grt the docker to shut down `docker compose stop`, try simply logging out or restarting pc

**Comment by terriblenecktie** [comment]
> particld is still running / wasnt shut down. If you cant grt the docker to shut down `docker compose stop`, try simply logging out or restarting pc

@nahuhh I've already tried that multiple times - I did a couple of full shutdown and restarts of my PC. Doesn't change anything. I think the daemon crashed so my suspicion is the cleanup operations like [this function](https://github.com/basicswap/basicswap/blob/75ad5a5b4d7cae171794324f1b870538159bf5cb/basicswap/basicswap.py#L895) didn't fully finish. Let me know if you have any other suggestions.

**Comment by nahuhh** [comment]
Are you also running particl desktop or marketplace?

**Comment by terriblenecktie** [comment]
@nahuhh Nope no particl components at all. Just running purely BasicSwap via Docker. If you really think this is due to something running in the background (although it feels pretty unlikely), any idea how I can confirm this? I'm not sure how to check for running daemons

**Comment by nahuhh** [comment]
`pidof particld` in the terminal

**Comment by terriblenecktie** [comment]
Running `pidof particld` gives no results. Also tried `ps -aux | grep particld`. Any suggestions how I can go about fixing this without needing to modify the rpcauth?

**Comment by nahuhh** [comment]
You dont have to modify rpcauth etc.

Have you loaded any of the wallets yet or is this a fresh install?

its probably a corrupt blockchain due to running out of storage.
Easiest is to resync the blockchain

**Comment by bacoinin** [comment]
> I'm running basicswap via docker. While the coins were syncing it crashed due to file storage issues and I don't think it shut down gracefully. When I tried to `docker compose up` again I get an error when it tries to read the cookie.
> 
> ```
> swapclient-1  | 2024-07-11 17:59:25 WARNING : Error, iteration 19: [Errno 2] No such file or directory: '/coindata/particl/particl.pid'
> swapclient-1  | 2024-07-11 17:59:25 ERROR : Unable to read authcookie for PART, /coindata/particl/.cookie, datadir pid -1, daemon pid 18. Error: Mismatched pid
> swapclient-1  | Traceback (most recent call last):
> swapclient-1  |   File "/usr/local/lib/python3.10/dist-packages/basicswap/basicswap.py", line 769, in setCoinRunParams
> swapclient-1  |     assert (datadir_pid == cc['pid']), 'Mismatched pid'
> swapclient-1  | AssertionError: Mismatched pid
> swapclient-1  | 
> swapclient-1  | During handling of the above exception, another exception occurred:
> swapclient-1  | 
> swapclient-1  | Traceback (most recent call last):
> swapclient-1  |   File "/usr/local/lib/python3.10/dist-packages/bin/basicswap_run.py", line 302, in runClient
> swapclient-1  |     swap_client.start()
> swapclient-1  |   File "/usr/local/lib/python3.10/dist-packages/basicswap/basicswap.py", line 798, in start
> swapclient-1  |     self.setCoinRunParams(c)
> swapclient-1  |   File "/usr/local/lib/python3.10/dist-packages/basicswap/basicswap.py", line 774, in setCoinRunParams
> swapclient-1  |     raise ValueError('Error, terminating')
> swapclient-1  | ValueError: Error, terminating
> ```
> 
> Is there any way I can fix this? I've tried to fiddle with the code but I can't seem to get it to finish the `setCoinRunParams` method without erroring. The only part that seems to matter in that is setting the `cc['rpcauth']` and I tried various defaults for this but couldn't get it to work fully. Can I somehow manually supply rpcauth or set a default cookie somehow?
> 
> Once I can get it running again I'll make sure it shuts down gracefully. I would just prefer not to have to delete the entire chain sync's progress to get it working.

It looks like your Particl Core node is unable to start. Check the coindata/particl/debug.log to see if that is the case and if so, what is the reason that prevents the start-up.
