### ISSUE TITLE
Installation issue preparing datadir

### ISSUE THREAD

**Issue by link-leo** [basicswap/basicswap#59]
Encountered error [installing](https://github.com/tecnovert/basicswap/blob/master/doc/install.md) on Linux Mint:

```
(venv) me@computer:~/coinswaps/basicswap$ CURRENT_XMR_HEIGHT=$(curl https://localmonero.co/blocks/api/get_stats | jq .height)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   169    0   169    0     0    243      0 --:--:-- --:--:-- --:--:--   243
(venv) me@computer:~/coinswaps/basicswap$ basicswap-prepare --datadir=$SWAP_DATADIR --withcoins=monero --xmrrestoreheight=$CURRENT_XMR_HEIGHT
Traceback (most recent call last):
  File "/home/me/coinswaps/venv/bin/basicswap-prepare", line 33, in <module>
    sys.exit(load_entry_point('basicswap==0.12.7', 'console_scripts', 'basicswap-prepare')())
  File "/home/me/coinswaps/venv/bin/basicswap-prepare", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/me/coinswaps/venv/lib/python3.10/site-packages/bin/basicswap_prepare.py", line 33, in <module>
    from basicswap.basicswap import BasicSwap
  File "/home/me/coinswaps/venv/lib/python3.10/site-packages/basicswap/basicswap.py", line 69, in <module>
    from .messages_pb2 import (
  File "/home/me/coinswaps/venv/lib/python3.10/site-packages/basicswap/messages_pb2.py", line 34, in <module>
    _descriptor.EnumValueDescriptor(
  File "/home/me/coinswaps/venv/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 789, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
(venv) me@computer:~/coinswaps/basicswap$
```

**Comment by nahuhh** [comment]
Delete coinswaps folder

Use installer: (temporary link) https://github.com/nahuhh/basicswap-bash/releases/tag/beta

Will move to here after confirming mac support:
https://github.com/nahuhh/basicswap-bash/releases/latest

**Comment by seasharpfoss** [comment]
@link-leo Did this solve your problem or do you need more help?

**Comment by nahuhh** [comment]
The linked installer works around the issue my installing the correct protobuf version within the venv

**Comment by nahuhh** [comment]
@link-leo the protobuf issues should be remedied on latest versions. Please reopen if youre still having issues
