### ISSUE TITLE
Adding Litecoin does not work

### ISSUE THREAD

**Issue by Shadow27374** [basicswap/basicswap#88]
I use the following instructions: https://academy.particl.io/en/latest/basicswap-guides/basicswapguides_addremovecoins.html

So first stop the container, then export the path again and finally:

docker run --rm -t --name swap_prepare -v $COINDATA_PATH:/coindata i_swapclient basicswap-prepare --datadir=/coindata --addcoin=litecoin

Problem is now:
```
INFO:root:BasicSwap prepare script 0.13.0
INFO:root:Python version: 3.10.12
INFO:root:Data dir: /coindata
INFO:root:Bin dir: /coindata/bin
INFO:root:Chain: mainnet
INFO:root:WALLET_ENCRYPTION_PWD is not set
INFO:root:Adding coin: litecoin
2024-05-20 22:06:18 INFO : Network: mainnet
INFO:root:Starting node /coindata/bin/particl/particld -datadir=/coindata/particl
2024-05-20 22:06:18 DEBUG : Reading PART rpc credentials from auth cookie /coindata/particl/.cookie
2024-05-20 22:06:18 WARNING : Error, iteration 0: [Errno 2] No such file or directory: '/coindata/particl/particl.pid'
2024-05-20 22:06:18 WARNING : Can't connect to PART RPC: RPC error {'code': -28, 'message': 'Loading block index…'}.  Trying again in 1 second/s, 1/21.
2024-05-20 22:06:19 WARNING : Can't connect to PART RPC: RPC error {'code': -28, 'message': 'Loading block index…'}.  Trying again in 2 second/s, 2/21.
2024-05-20 22:06:21 WARNING : Can't connect to PART RPC: RPC error {'code': -28, 'message': 'Loading block index…'}.  Trying again in 3 second/s, 3/21.
2024-05-20 22:06:24 WARNING : Can't connect to PART RPC: RPC error {'code': -28, 'message': 'Loading block index…'}.  Trying again in 4 second/s, 4/21.
2024-05-20 22:06:28 WARNING : Can't connect to PART RPC: RPC error {'code': -28, 'message': 'Loading block index…'}.  Trying again in 5 second/s, 5/21.
INFO:root:Particl Wallet is encrypted
2024-05-20 22:06:33 INFO : Finalise
INFO:root:Interrupting 14
Traceback (most recent call last):
  File "/usr/local/bin/basicswap-prepare", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/bin/basicswap_prepare.py", line 1790, in main
    test_particl_encryption(data_dir, settings, chain, use_tor_proxy)
  File "/usr/local/lib/python3.10/dist-packages/bin/basicswap_prepare.py", line 1164, in test_particl_encryption
    raise ValueError('Must set WALLET_ENCRYPTION_PWD to add coin when Particl wallet is encrypted')
ValueError: Must set WALLET_ENCRYPTION_PWD to add coin when Particl wallet is encrypted
```

**Comment by nahuhh** [comment]
change this step
```
export COINDATA_PATH=/var/data/coinswaps
```

to
```
export COINDATA_PATH=/var/data/coinswaps
 WALLET_ENCRYPTION_PWD="YourPasswordHere"
```

Make sure to include a space before the word "export" for the password line

**Comment by nahuhh** [comment]
It still shows

```
INFO:root:BasicSwap prepare script 0.13.0 INFO:root:Python version: 3.10.12 INFO:root:Data dir: /coindata INFO:root:Bin dir: /coindata/bin INFO:root:Chain: mainnet INFO:root:WALLET_ENCRYPTION_PWD is not set
```
?

**Comment by nahuhh** [comment]
Try adding it to the .env file

**Comment by nahuhh** [comment]
@Shadow27374 

apologies.
the correct syntax should be adding the variable inside of the docker command. Something like:

```
docker-compose run --rm -e $COINDATA_PATH:/coindata WALLET_ENCRYPTION_PWD=passwordhere swapclient basicswap-prepare --datadir=/coindata --addcoin=litecoin
```
